services:
  - type: web
    name: spacy-ginza-online-demonstration
    env: python
    plan: free
    buildCommand: pipenv sync
    startCommand: gunicorn --workers=4 --worker-class=uvicorn.workers.UvicornWorker main:app
    envVars:
    - key: PYTHON_VERSION
      value: 3.9
